server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 301 /docs/;
  }

  location = /docs {
    return 301 /docs/;
  }

  location /docs/ {
    try_files $uri $uri/ /docs/index.html;
  }
}
